version: '3' 
services:

  namenode:
    image: fjardim/namenode_sqoop
    container_name: namenode
    hostname: namenode
    volumes:
      - ./base/hdfs/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./base/hadoop/hadoop-hive.env
    ports:
      - "50070:50070"
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.5

  datanode1:
    image: fjardim/datanode
    container_name: datanode1
    hostname: datanode1
    volumes:
      - ./base/hdfs/datanode1:/hadoop/dfs/data
    env_file:
      - ./base/hadoop/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    depends_on:
      - namenode
    ports:
      - "50075:50075"
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.6

  datanode2:
    image: fjardim/datanode
    container_name: datanode2
    hostname: datanode2
    volumes:
      - ./base/hdfs/datanode2:/hadoop/dfs/data
    env_file:
      - ./base/hadoop/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    depends_on:
      - namenode
    ports:
      - "50080:50075"
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.7

  datanode3:
    image: fjardim/datanode
    container_name: datanode3
    hostname: datanode3
    volumes:
      - ./base/hdfs/datanode3:/hadoop/dfs/data
    env_file:
      - ./base/hadoop/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    depends_on:
      - namenode
    ports:
      - "50085:50075"
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.8
  
  hive-server:
    image: fjardim/hive
    container_name: hive-server
    hostname: hive_server
    env_file:
      - ./base/hadoop/hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.9
  
  hive-metastore:
    image: fjardim/hive
    container_name: hive_metastore
    hostname: hive_metastore
    env_file:
      - ./base/hadoop/hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-postgresql
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.10
  
  hive-metastore-postgresql:
    image: fjardim/hive-metastore
    container_name: hive-metastore-postgresql
    hostname: hive_metastore_postgresql
    volumes:
      - ./base/postgresql:/var/lib/postgresql/data
    depends_on:
      - datanode1
      - datanode2
      - datanode3
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.11

  hue:
    image: fjardim/hue
    hostname: hue
    container_name: hue
    dns: 8.8.8.8
    ports:
    - "8888:8888"
    volumes:
      - ./base/hue/hue-overrides.ini:/usr/share/hue/desktop/conf/z-hue.ini
    depends_on:
      - "database"
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.12
  
  database:
    image: fjardim/mysql
    container_name: database
    hostname: database
    ports:
        - "33061:3306"
    deploy:
      resources:
        limits:
          memory: 500m
    command: mysqld --innodb-flush-method=O_DSYNC --innodb-use-native-aio=OFF --init-file /data/application/init.sql
    volumes:
        - ./base/mysql/data:/var/lib/mysql
        - ./base/mysql/init.sql:/data/application/init.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: hue
        MYSQL_USER: root
        MYSQL_PASSWORD: secret
    networks:
      net_pet:
        ipv4_address: 172.27.1.13

  zookeeper:
    image: fjardim/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./base/zookeeper:/opt/zookeeper-3.4.6/data
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.14

  kafka:
    image: fjardim/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    volumes:
      - ./base/kafka:/kafka/kafka-logs-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.15

  presto-coordinator:
    image: fjardim/prestodb
    container_name: presto
    hostname: presto
    ports:
      - 8080:8080
    depends_on:
      - hive-server  
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.16

  hbase-master:
    image: fjardim/hbase-master
    container_name: hbase-master
    hostname: hbase-master
    env_file:
      - ./base/hbase/hbase-standalone.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 datanode2:50080 datanode3:50085 zookeeper:2181"
    ports:
      - 16010:16010
    depends_on:
      - namenode
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.17
  
  mongo:
    image: fjardim/mongo
    container_name: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./base/mongo:/data
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.18
 
  mongo-express:
    image: fjardim/mongo-express
    container_name: mongo_express
    hostname: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    deploy:
      resources:
        limits:
          memory: 200m
    networks:
      net_pet:
        ipv4_address: 172.27.1.19
 
  kafkamanager:
    image: fjardim/kafkamanager
    container_name: kafkamanager
    hostname: kafkamanager
    environment: 
      ZK_HOSTS: zookeeper:2181
    ports:
      - 9000:9000
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          memory: 200m
    networks:
      net_pet:
        ipv4_address: 172.27.1.20
 
  metabase:
    image: fjardim/metabase
    container_name: metabase
    hostname: metabase
    volumes:
      - ./base/metabase/data:/metabase-data
    environment:
      MB_DB_FILE: "/metabase-data/metabase.db"
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      net_pet:
        ipv4_address: 172.27.1.21

  streamsets:
    image: streamsets/datacollector:3.13.0-latest
    container_name: streamsets
    hostname: streamsets
    ports:
      - "18630:18630"
    networks:
      net_pet:
        ipv4_address: 172.27.1.22
  
  storm:
    image: fmantuano/apache-storm:develop
    container_name: storm
    hostname: storm
    ports:
          - "8090:8080"
          - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      net_pet:
        ipv4_address: 172.27.1.23
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    hostname: nifi
    ports:
      - 9090:9090
      - 8443:8443
    environment:
      - NIFI_WEB_HTTP_PORT=9090
    networks:
      net_pet:
        ipv4_address: 172.27.1.25
    deploy:
      resources:
        limits:
          memory: 500m

  zeppelin:
    image: apache/zeppelin:0.8.2
    container_name: zeppelin
    hostname: zeppelin
    depends_on:
      - jupyter-spark
      - livy
    ports:
      - "7077:7077"
    volumes:
      - ./data/zeppelin/logs:/logs
      - ./data/zeppelin/notebook:/notebook
      - ./data/zeppelin/conf/interpreter.json:/zeppelin/conf/interpreter.json
    environment:
      ZEPPELIN_NOTEBOOK_DIR: /notebook
      ZEPPELIN_PORT: 7077
      ZEPPELIN_LOG_DIR: /logs
    networks:
      net_pet:
        ipv4_address: 172.27.1.28
        
  livy:
    image: panovvv/livy:2.5.2
    container_name: livy
    #build: '../livy-docker'
    hostname: livy
    depends_on:
      - jupyter-spark
    volumes:
      - ./livy_batches:/livy_batches
      - ./data:/data
    environment:
      - SPARK_MASTER=yarn
      # Intentionally not specified - if it's set here, then we can't override it
      # via REST API ("conf"={} map)
      # Can be client or cluster
      #      - SPARK_DEPLOY_MODE=client
      - LOCAL_DIR_WHITELIST=/data/batches/
      - ENABLE_HIVE_CONTEXT=false
      # Defaults are fine for variables below. Uncomment to change them.
      #      - LIVY_HOST=0.0.0.0
      #      - LIVY_PORT=8998
    ports:
      - 8998:8998
    networks:
      net_pet:
        ipv4_address: 172.27.1.29      

   jupyter-spark:
    image: fjardim/jupyter-spark
    hostname: jupyter-spark
    container_name: jupyter-spark
    command: notebook
    env_file:
      - ./base/jupyter/jupyter.env
    ports:
      - 8889:8889
      - 4040:4040
      - 4041:4041
      - 4042:4042
      - 4043:4043
    volumes:
       - ./base/notebooks:/mnt/notebooks/
    environment:
       SPARK_MASTER: local[*]
       JUPYTER_PORT: 8889
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      net_pet:
        ipv4_address: 172.27.1.24

networks:
  net_pet:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16